token_file: ".token"
log_level: "INFO"
expa:
  client_id:
  client_secret:
  opportunities:
trello:
  api_key:
  token:
  board_id:
  cards_filename:
discord:
  dc_token:
  dc_channel_id:
  dc_messages_filename: