[tool.black]
target-version = ["py39", "py310"]
exclude = "generated"

[tool.isort]
profile = "black"
force_sort_within_sections = true
known_first_party = [
    "receptiontool",
    "tests",
]
forced_separate = [
    "tests",
]
combine_as_imports = true
