name: CI

on:
  push:
    branches:
    - master
  pull_request: ~

env:
  DEFAULT_PYTHON: "3.10"

jobs:
  lint-flake8:
    name: Check flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.DEFAULT_PYTHON }}
      uses: actions/setup-python@v2
      with:
        cache: pip
        python-version: ${{ env.DEFAULT_PYTHON }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements_test.txt
    - name: Register flake8 problem matcher
      run: |
        echo "::add-matcher::.github/workflows/matchers/flake8.json"
    - name: Run flake8
      run: |
        flake8
  lint-black:
    name: Check black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.DEFAULT_PYTHON }}
      uses: actions/setup-python@v2
      with:
        cache: pip
        python-version: ${{ env.DEFAULT_PYTHON }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements_test.txt
    - name: Run black
      run: black .
  lint-isort:
    name: Check isort
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.DEFAULT_PYTHON }}
      uses: actions/setup-python@v2
      with:
        cache: pip
        python-version: ${{ env.DEFAULT_PYTHON }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements_test.txt
    - name: Run isort
      run: isort .
  mypy:
    name: Check mypy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.DEFAULT_PYTHON }}
      uses: actions/setup-python@v2
      with:
        cache: pip
        python-version: ${{ env.DEFAULT_PYTHON }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements_test.txt
    - name: Register mypy problem matcher
      run: |
        echo "::add-matcher::.github/workflows/matchers/mypy.json"
    - name: Run mypy
      run: |
        mypy receptiontool/
