name: CI

on: [push]

env:
  DEFAULT_PYTHON: "3.10"

jobs:
  lint-flake8:
    name: Check flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.DEFAULT_PYTHON }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.DEFAULT_PYTHON }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements_test.txt
    - name: Run flake8
      run: |
        flake8 src/
  mypy:
    name: Check mypy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.DEFAULT_PYTHON }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.DEFAULT_PYTHON }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements_test.txt
    - name: Run mypy
      run: |
        mypy src/
